### ISSUE TITLE
Image errors on both dashboard and quicklook

### ISSUE THREAD

**Issue by timthedevguy** [archan937/topup#3]
I've tested this by using my own local files and linking directly to the script on your site.  The images appear to be wanting to draw, but they just aren't quite there or aligned properly.  Here is a screenshot (the test site is only on my local machine so a pic is all I can give ya)

http://www.binarymethod.com/images/topup.png

**Comment by timthedevguy** [comment]
Oops...
Using OS X Snow Leopard  10.6.1
Safari Version 4.0.3 (6531.9) &
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5

**Comment by archan937** [comment]
Hi god ;),

That looks very weird! It seems that both the quicklook and dashboard layout are being rendered. Did you set the layout class manually or something? If so, don't do that :D

Anyhow, I can't help you any further unless you mail me the source at paul.engel@holder.nl or put the page online so I can debug it with Firebug. I'll be standby for your mail ;). Good luck.

**Comment by timthedevguy** [comment]
Ok, I uploaded everything to the live site, you can see whats going on here -> http://www.binarymethod.com/drupal/?q=bghudappkit

Now when I try it just stays stuck on loading bar.  Here's the actual image it's trying to display. http://www.binarymethod.com/drupal/files/images/bghudappkit/BGHUDAppKit.png

**Comment by timthedevguy** [comment]
Fixed the stuck loading bar, it was my fault, caps error :)  Still displays the weird images.

**Comment by timthedevguy** [comment]
Close this issue, it was a problem with a CSS element with the same name in another CSS file.  tbody is a common one I guess.

Thanks for the help!!

**Comment by archan937** [comment]
No prob. Good luck with the further implementation of your site!
