### ISSUE TITLE
Current image variable is not updated when relaunching TopUp.

### ISSUE THREAD

**Issue by timo-bes** [archan937/topup#4]
When an image within a group is clicked for the second time after closing TopUp, the next image button will show the image after the one that was last displayed before TopUp was closed.
For example go to http://gettopup.com/examples (this works in Firefox on OS X, i didn't try other browsers). Click on the green apple wallpaper within the grouped links section and close TopUp again. Click the second image and hit the next image button. This will just display the same image again, because it comes after the green wallpaper, on which TopUp was closed.

**Comment by archan937** [comment]
Thanks BeezyT for reporting this issue. I have released a new version (1.6.2) of TopUp in which this issue is resolved. See http://gettopup.com/changelog.

Greets,
Paul.
